# Generated by Django 5.1.2 on 2024-10-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_submitted', models.BooleanField(default=False)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='verification/id_proofs/')),
                ('medical_license', models.FileField(blank=True, null=True, upload_to='verification/medical_licenses/')),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='verification/degree_certificates/')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('medical_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='doctors.doctor')),
            ],
        ),
    ]
