# Generated by Django 5.1.2 on 2024-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_is_verified_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='form_submitted',
        ),
        migrations.AddField(
            model_name='doctor',
            name='form_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
