name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Specify Python version (use 3.8 or higher)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up the database environment variables
      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=myproject.settings" >> $GITHUB_ENV
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

      # Step 5: Run Django migrations
      - name: Run migrations
        run: |
          python manage.py migrate

      # Step 6: Run Django tests
      - name: Run tests
        run: |
          python manage.py test

      # Step 7: Linting with flake8 (optional)
      - name: Run flake8
        run: |
          pip install flake8
          flake8 .
